[build]
  command = "echo 'Skip build'"  # Пропускаем сборку, если не требуется
  publish = "public"             # Папка с фронтендом
  functions = "functions"        # Папка для serverless-функций

[build.environment]
  NODE_VERSION = "22.14.0"       # Фиксируем версию Node.js

[functions]
  node_bundler = "esbuild"       # Ускоряет деплой функций
  external_node_modules = ["@supabase/supabase-js"]  # Исключаем лишние зависимости

# Перенаправления для SPA (учтена папка public/)
[[redirects]]
  from = "/*"
  to = "/public/:splat"          # Все запросы перенаправляем в public/
  status = 200
  force = true                   # Приоритет над дефолтными правилами

[[redirects]]
  from = "/view.html"
  to = "/public/view.html"       # Явное перенаправление для view.html
  status = 200

# Настройки кэширования для статики
[[headers]]
  for = "/public/*"              # Применяем только к файлам в public/
  [headers.values]
    Cache-Control = "public, max-age=3600"  # Кэшировать на 1 час
    Access-Control-Allow-Origin = "*"

# CORS для функций (оптимизированная версия)
[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://carrytest.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Max-Age = "86400"        # Кэшировать CORS-префлайт на 24 часа