[build]
  command = "echo 'Skip build'"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22.14.0"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Основные перенаправления
[[redirects]]
  from = "/*"
  to = "/public/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/public/index.html"  # Явное указание index.html
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/public/index.html"  # Дублирующее правило для index
  status = 200

[[redirects]]
  from = "/view.html"
  to = "/public/view.html"
  status = 200

# Заголовки
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://carrytest.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Max-Age = "86400"