[build]
  command = "echo 'Skip'"  # Пропускаем сборку (если не нужно)
  publish = "public"        # Папка с фронтендом
  functions = "functions"   # Папка для serverless-функций

# Оптимизация функций (добавляем)
[functions]
  node_bundler = "esbuild"  # Ускоряет деплой функций
  external_node_modules = ["@supabase/supabase-js"]  # Исключает лишние зависимости

# Перенаправления для SPA (ваш существующий код)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/view.html"
  to = "/view.html"
  status = 200

# Важно: разрешаем CORS для функций (добавляем)
[[headers]]
  for = "/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://carrytest.netlify.app"  # Разрешаем доступ только с carrytest.netlify.app
    Access-Control-Allow-Methods = "GET, POST"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Credentials = "true"  # Если требуется передавать куки или другие данные с запросом

# Устанавливаем версию Node.js
[build.environment]
  NODE_VERSION = "22.14.0"
